linked-grails/grails-app/domain/com/linkedgrails/Atualizacao.groovy
package com.linkedgrails

class Atualizacao {

//    Pessoa responsavel

    Date dateCreated
    Date lastUpdated

    static belongsTo = [responsavel: Pessoa]

    static constraints = {
        dateCreated nullable: true
        lastUpdated nullable: true
    }
}

linked-grails/grails-app/controllers/com/linkedgrails/AtualizacaoController.groovy
package com.linkedgrails

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class AtualizacaoController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Atualizacao.list(params), model:[atualizacaoCount: Atualizacao.count()]
    }

    def show(Atualizacao atualizacao) {
        respond atualizacao
    }

    def create() {
        respond new Atualizacao(params)
    }

    @Transactional
    def save(Atualizacao atualizacao) {
        if (atualizacao == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (atualizacao.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond atualizacao.errors, view:'create'
            return
        }

        atualizacao.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'atualizacao.label', default: 'Atualizacao'), atualizacao.id])
                redirect atualizacao
            }
            '*' { respond atualizacao, [status: CREATED] }
        }
    }

    def edit(Atualizacao atualizacao) {
        respond atualizacao
    }

    @Transactional
    def update(Atualizacao atualizacao) {
        if (atualizacao == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (atualizacao.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond atualizacao.errors, view:'edit'
            return
        }

        atualizacao.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'atualizacao.label', default: 'Atualizacao'), atualizacao.id])
                redirect atualizacao
            }
            '*'{ respond atualizacao, [status: OK] }
        }
    }

    @Transactional
    def delete(Atualizacao atualizacao) {

        if (atualizacao == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        atualizacao.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'atualizacao.label', default: 'Atualizacao'), atualizacao.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'atualizacao.label', default: 'Atualizacao'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

linked-grails/grails-app/views/atualizacao/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'atualizacao.label', default: 'Atualizacao')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-atualizacao" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-atualizacao" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.atualizacao}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.atualizacao}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.atualizacao}" method="POST">
                <fieldset class="form">
                    <f:all bean="atualizacao"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

linked-grails/grails-app/views/atualizacao/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'atualizacao.label', default: 'Atualizacao')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-atualizacao" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-atualizacao" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.atualizacao}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.atualizacao}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.atualizacao}" method="PUT">
                <g:hiddenField name="version" value="${this.atualizacao?.version}" />
                <fieldset class="form">
                    <f:all bean="atualizacao"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

linked-grails/grails-app/views/atualizacao/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'atualizacao.label', default: 'Atualizacao')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-atualizacao" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-atualizacao" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${atualizacaoList}" />

            <div class="pagination">
                <g:paginate total="${atualizacaoCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

linked-grails/grails-app/views/atualizacao/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'atualizacao.label', default: 'Atualizacao')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-atualizacao" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-atualizacao" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="atualizacao" />
            <g:form resource="${this.atualizacao}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.atualizacao}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>